# Generated by Django 4.0.5 on 2022-09-13 01:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('In', 'Inbound'), ('On', 'Outbound')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('days', models.CharField(blank=True, choices=[('Wek', 'Weekdays'), ('Sun', 'Sundays'), ('Sat', 'Saturdays'), ('Hol', 'Public Holidays')], max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('direction_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='western_cape.direction')),
                ('stops', models.ManyToManyField(to='western_cape.stop')),
            ],
        ),
        migrations.AddField(
            model_name='direction',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='western_cape.line'),
        ),
        migrations.AddField(
            model_name='direction',
            name='stops',
            field=models.ManyToManyField(to='western_cape.stop'),
        ),
    ]
