# Generated by Django 4.0.5 on 2022-09-13 03:20

from django.db import migrations, models
import django.db.models.deletion
import uuid

class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='line',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='trains',
        ),
        migrations.AddField(
            model_name='line',
            name='direction',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='western_cape.direction'),
        ),
    ]
