# Generated by Django 4.0.5 on 2022-09-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0005_line_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrival',
            name='platform_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='arrival',
            name='arrival_time',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
