# Generated by Django 4.0.5 on 2022-09-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0007_remove_direction_stops_stop_direction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='direction',
        ),
        migrations.AddField(
            model_name='direction',
            name='stops',
            field=models.ManyToManyField(to='western_cape.stop'),
        ),
    ]
