# Generated by Django 4.0.5 on 2022-09-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0008_remove_stop_direction_direction_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='stops',
        ),
        migrations.RemoveField(
            model_name='line',
            name='direction',
        ),
        migrations.AddField(
            model_name='direction',
            name='line',
            field=models.ManyToManyField(to='western_cape.line'),
        ),
    ]
