# Generated by Django 4.0.5 on 2022-09-13 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0009_remove_direction_stops_remove_line_direction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='line',
        ),
        migrations.AddField(
            model_name='line',
            name='direction',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='western_cape.direction'),
        ),
    ]
