# Generated by Django 4.0.5 on 2022-09-13 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0012_remove_direction_line_direction_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='line',
            name='train_stop_time',
        ),
    ]
