# Generated by Django 4.0.5 on 2022-09-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0013_remove_line_train_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='western_cape.line'),
        ),
    ]
