# Generated by Django 4.0.5 on 2022-09-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0014_stop_line'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stop',
            name='line',
        ),
        migrations.AddField(
            model_name='stop',
            name='line',
            field=models.ManyToManyField(to='western_cape.line'),
        ),
    ]
