# Generated by Django 4.0.5 on 2022-09-16 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0015_remove_stop_line_stop_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='line',
            name='number',
            field=models.IntegerField(choices=[(1, 'ONE'), (2, 'TWO')], default=1),
        ),
    ]
