# Generated by Django 4.0.5 on 2022-09-18 08:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0017_alter_direction_id_alter_line_id_alter_stop_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('only_stops_at', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='western_cape.stop')),
            ],
        ),
        migrations.AddField(
            model_name='train',
            name='train_stops',
            field=models.ManyToManyField(to='western_cape.trainstop'),
        ),
    ]
