# Generated by Django 4.0.5 on 2022-09-18 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0018_trainstop_train_train_stops'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='train',
            name='train_stops',
        ),
        migrations.RemoveField(
            model_name='trainstop',
            name='only_stops_at',
        ),
        migrations.AddField(
            model_name='trainstop',
            name='only_stops_at',
            field=models.ManyToManyField(to='western_cape.arrival'),
        ),
    ]
