# Generated by Django 4.0.5 on 2022-09-18 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0019_remove_train_train_stops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstop',
            name='train_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
