# Generated by Django 4.0.5 on 2022-09-20 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0021_alter_stop_id_alter_train_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.IntegerField(default=0)),
                ('stop_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_stop', to='western_cape.stop')),
                ('stop_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_stop', to='western_cape.stop')),
            ],
        ),
    ]
