# Generated by Django 4.0.5 on 2022-09-20 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0022_edge'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Edge',
            new_name='GraphEdge',
        ),
    ]
