# Generated by Django 4.0.5 on 2022-09-20 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0023_rename_edge_graphedge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphedge',
            name='stop_from',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='graphedge',
            name='stop_to',
            field=models.CharField(max_length=200),
        ),
    ]
