# Generated by Django 4.0.5 on 2022-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0024_alter_graphedge_stop_from_alter_graphedge_stop_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphedge',
            name='interchange',
            field=models.BooleanField(default=False),
        ),
    ]
