# Generated by Django 4.0.5 on 2022-09-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0025_graphedge_interchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphedge',
            name='interchange',
        ),
        migrations.AddField(
            model_name='stop',
            name='interchange',
            field=models.BooleanField(default=False),
        ),
    ]
