# Generated by Django 4.0.5 on 2022-09-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0027_graphedge_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainstop',
            name='stops',
            field=models.ManyToManyField(blank=True, null=True, to='western_cape.stop'),
        ),
    ]
