# Generated by Django 4.0.5 on 2022-09-22 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('western_cape', '0028_trainstop_stops'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstop',
            name='stops',
            field=models.ManyToManyField(blank=True, to='western_cape.stop'),
        ),
    ]
