# Generated by Django 4.0.5 on 2022-09-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
            ],
        ),
    ]
